name: tests

on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ['3.7', '3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          sudo apt install abcm2ps
          pip install .

      - name: Style
        run: |
          flake8

      - name: Test
        run: |
          pytest abc_sphinx/tests/
